//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.01 at 09:58:58 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.visi.nl/schemas/20071218", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package nl.visi.interaction_schema;
