//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.01 at 09:58:58 PM CET 
//


package nl.visi.interaction_schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{http://www.visi.nl/schemas/20071218}AppendixType"/>
 *         &lt;element ref="{http://www.visi.nl/schemas/20071218}ComplexElementType"/>
 *         &lt;element ref="{http://www.visi.nl/schemas/20071218}ElementCondition"/>
 *         &lt;element ref="{http://www.visi.nl/schemas/20071218}GroupType"/>
 *         &lt;element ref="{http://www.visi.nl/schemas/20071218}MessageInTransactionType"/>
 *         &lt;element ref="{http://www.visi.nl/schemas/20071218}MessageType"/>
 *         &lt;element ref="{http://www.visi.nl/schemas/20071218}OrganisationType"/>
 *         &lt;element ref="{http://www.visi.nl/schemas/20071218}PersonType"/>
 *         &lt;element ref="{http://www.visi.nl/schemas/20071218}ProjectType"/>
 *         &lt;element ref="{http://www.visi.nl/schemas/20071218}RoleType"/>
 *         &lt;element ref="{http://www.visi.nl/schemas/20071218}SimpleElementType"/>
 *         &lt;element ref="{http://www.visi.nl/schemas/20071218}TransactionPhaseType"/>
 *         &lt;element ref="{http://www.visi.nl/schemas/20071218}TransactionType"/>
 *         &lt;element ref="{http://www.visi.nl/schemas/20071218}UserDefinedType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "appendixTypeOrComplexElementTypeOrElementCondition"
})
@XmlRootElement(name = "visiXML_VISI_Systematics")
public class VisiXMLVISISystematics {

    @XmlElements({
        @XmlElement(name = "ElementCondition", type = ElementConditionType.class),
        @XmlElement(name = "GroupType", type = GroupTypeType.class),
        @XmlElement(name = "SimpleElementType", type = SimpleElementTypeType.class),
        @XmlElement(name = "MessageType", type = MessageTypeType.class),
        @XmlElement(name = "AppendixType", type = AppendixTypeType.class),
        @XmlElement(name = "MessageInTransactionType", type = MessageInTransactionTypeType.class),
        @XmlElement(name = "TransactionPhaseType", type = TransactionPhaseTypeType.class),
        @XmlElement(name = "ProjectType", type = ProjectTypeType.class),
        @XmlElement(name = "RoleType", type = RoleTypeType.class),
        @XmlElement(name = "UserDefinedType", type = UserDefinedTypeType.class),
        @XmlElement(name = "ComplexElementType", type = ComplexElementTypeType.class),
        @XmlElement(name = "PersonType", type = PersonTypeType.class),
        @XmlElement(name = "OrganisationType", type = OrganisationTypeType.class),
        @XmlElement(name = "TransactionType", type = TransactionTypeType.class)
    })
    protected List<ElementType> appendixTypeOrComplexElementTypeOrElementCondition;

    /**
     * Gets the value of the appendixTypeOrComplexElementTypeOrElementCondition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the appendixTypeOrComplexElementTypeOrElementCondition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAppendixTypeOrComplexElementTypeOrElementCondition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ElementConditionType }
     * {@link GroupTypeType }
     * {@link SimpleElementTypeType }
     * {@link MessageTypeType }
     * {@link AppendixTypeType }
     * {@link MessageInTransactionTypeType }
     * {@link TransactionPhaseTypeType }
     * {@link ProjectTypeType }
     * {@link RoleTypeType }
     * {@link UserDefinedTypeType }
     * {@link ComplexElementTypeType }
     * {@link PersonTypeType }
     * {@link OrganisationTypeType }
     * {@link TransactionTypeType }
     * 
     * 
     */
    public List<ElementType> getAppendixTypeOrComplexElementTypeOrElementCondition() {
        if (appendixTypeOrComplexElementTypeOrElementCondition == null) {
            appendixTypeOrComplexElementTypeOrElementCondition = new ArrayList<ElementType>();
        }
        return this.appendixTypeOrComplexElementTypeOrElementCondition;
    }

}
