//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 01:30:30 PM CET 
//


package nl.visi.schemas._20160331;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ElementConditionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ElementConditionType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.visi.nl/schemas/20160331}elementType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="condition" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="helpInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="complexElements" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded">
 *                   &lt;element ref="{http://www.visi.nl/schemas/20160331}ComplexElementType"/>
 *                   &lt;element ref="{http://www.visi.nl/schemas/20160331}ComplexElementTypeRef"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="simpleElement" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{http://www.visi.nl/schemas/20160331}SimpleElementType"/>
 *                   &lt;element ref="{http://www.visi.nl/schemas/20160331}SimpleElementTypeRef"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="messageInTransaction" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{http://www.visi.nl/schemas/20160331}MessageInTransactionType"/>
 *                   &lt;element ref="{http://www.visi.nl/schemas/20160331}MessageInTransactionTypeRef"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ElementConditionType", propOrder = {
    "description",
    "condition",
    "helpInfo",
    "complexElements",
    "simpleElement",
    "messageInTransaction"
})
public class ElementConditionType
    extends ElementType
{

    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected String condition;
    protected String helpInfo;
    protected ElementConditionType.ComplexElements complexElements;
    protected ElementConditionType.SimpleElement simpleElement;
    protected ElementConditionType.MessageInTransaction messageInTransaction;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCondition(String value) {
        this.condition = value;
    }

    /**
     * Gets the value of the helpInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHelpInfo() {
        return helpInfo;
    }

    /**
     * Sets the value of the helpInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHelpInfo(String value) {
        this.helpInfo = value;
    }

    /**
     * Gets the value of the complexElements property.
     * 
     * @return
     *     possible object is
     *     {@link ElementConditionType.ComplexElements }
     *     
     */
    public ElementConditionType.ComplexElements getComplexElements() {
        return complexElements;
    }

    /**
     * Sets the value of the complexElements property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementConditionType.ComplexElements }
     *     
     */
    public void setComplexElements(ElementConditionType.ComplexElements value) {
        this.complexElements = value;
    }

    /**
     * Gets the value of the simpleElement property.
     * 
     * @return
     *     possible object is
     *     {@link ElementConditionType.SimpleElement }
     *     
     */
    public ElementConditionType.SimpleElement getSimpleElement() {
        return simpleElement;
    }

    /**
     * Sets the value of the simpleElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementConditionType.SimpleElement }
     *     
     */
    public void setSimpleElement(ElementConditionType.SimpleElement value) {
        this.simpleElement = value;
    }

    /**
     * Gets the value of the messageInTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link ElementConditionType.MessageInTransaction }
     *     
     */
    public ElementConditionType.MessageInTransaction getMessageInTransaction() {
        return messageInTransaction;
    }

    /**
     * Sets the value of the messageInTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementConditionType.MessageInTransaction }
     *     
     */
    public void setMessageInTransaction(ElementConditionType.MessageInTransaction value) {
        this.messageInTransaction = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded">
     *         &lt;element ref="{http://www.visi.nl/schemas/20160331}ComplexElementType"/>
     *         &lt;element ref="{http://www.visi.nl/schemas/20160331}ComplexElementTypeRef"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "complexElementTypeOrComplexElementTypeRef"
    })
    public static class ComplexElements {

        @XmlElements({
            @XmlElement(name = "ComplexElementType", type = ComplexElementTypeType.class),
            @XmlElement(name = "ComplexElementTypeRef", type = ComplexElementTypeTypeRef.class)
        })
        protected List<Object> complexElementTypeOrComplexElementTypeRef;

        /**
         * Gets the value of the complexElementTypeOrComplexElementTypeRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the complexElementTypeOrComplexElementTypeRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getComplexElementTypeOrComplexElementTypeRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ComplexElementTypeType }
         * {@link ComplexElementTypeTypeRef }
         * 
         * 
         */
        public List<Object> getComplexElementTypeOrComplexElementTypeRef() {
            if (complexElementTypeOrComplexElementTypeRef == null) {
                complexElementTypeOrComplexElementTypeRef = new ArrayList<Object>();
            }
            return this.complexElementTypeOrComplexElementTypeRef;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{http://www.visi.nl/schemas/20160331}MessageInTransactionType"/>
     *         &lt;element ref="{http://www.visi.nl/schemas/20160331}MessageInTransactionTypeRef"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "messageInTransactionType",
        "messageInTransactionTypeRef"
    })
    public static class MessageInTransaction {

        @XmlElement(name = "MessageInTransactionType")
        protected MessageInTransactionTypeType messageInTransactionType;
        @XmlElement(name = "MessageInTransactionTypeRef")
        protected MessageInTransactionTypeTypeRef messageInTransactionTypeRef;

        /**
         * Gets the value of the messageInTransactionType property.
         * 
         * @return
         *     possible object is
         *     {@link MessageInTransactionTypeType }
         *     
         */
        public MessageInTransactionTypeType getMessageInTransactionType() {
            return messageInTransactionType;
        }

        /**
         * Sets the value of the messageInTransactionType property.
         * 
         * @param value
         *     allowed object is
         *     {@link MessageInTransactionTypeType }
         *     
         */
        public void setMessageInTransactionType(MessageInTransactionTypeType value) {
            this.messageInTransactionType = value;
        }

        /**
         * Gets the value of the messageInTransactionTypeRef property.
         * 
         * @return
         *     possible object is
         *     {@link MessageInTransactionTypeTypeRef }
         *     
         */
        public MessageInTransactionTypeTypeRef getMessageInTransactionTypeRef() {
            return messageInTransactionTypeRef;
        }

        /**
         * Sets the value of the messageInTransactionTypeRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link MessageInTransactionTypeTypeRef }
         *     
         */
        public void setMessageInTransactionTypeRef(MessageInTransactionTypeTypeRef value) {
            this.messageInTransactionTypeRef = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{http://www.visi.nl/schemas/20160331}SimpleElementType"/>
     *         &lt;element ref="{http://www.visi.nl/schemas/20160331}SimpleElementTypeRef"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "simpleElementType",
        "simpleElementTypeRef"
    })
    public static class SimpleElement {

        @XmlElement(name = "SimpleElementType")
        protected SimpleElementTypeType simpleElementType;
        @XmlElement(name = "SimpleElementTypeRef")
        protected SimpleElementTypeTypeRef simpleElementTypeRef;

        /**
         * Gets the value of the simpleElementType property.
         * 
         * @return
         *     possible object is
         *     {@link SimpleElementTypeType }
         *     
         */
        public SimpleElementTypeType getSimpleElementType() {
            return simpleElementType;
        }

        /**
         * Sets the value of the simpleElementType property.
         * 
         * @param value
         *     allowed object is
         *     {@link SimpleElementTypeType }
         *     
         */
        public void setSimpleElementType(SimpleElementTypeType value) {
            this.simpleElementType = value;
        }

        /**
         * Gets the value of the simpleElementTypeRef property.
         * 
         * @return
         *     possible object is
         *     {@link SimpleElementTypeTypeRef }
         *     
         */
        public SimpleElementTypeTypeRef getSimpleElementTypeRef() {
            return simpleElementTypeRef;
        }

        /**
         * Sets the value of the simpleElementTypeRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link SimpleElementTypeTypeRef }
         *     
         */
        public void setSimpleElementTypeRef(SimpleElementTypeTypeRef value) {
            this.simpleElementTypeRef = value;
        }

    }

}
