//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 01:30:30 PM CET 
//


package nl.visi.schemas._20160331;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for MessageInTransactionTypeConditionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MessageInTransactionTypeConditionType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.visi.nl/schemas/20160331}elementType">
 *       &lt;sequence>
 *         &lt;element name="sendAfter" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded">
 *                   &lt;element ref="{http://www.visi.nl/schemas/20160331}MessageInTransactionType"/>
 *                   &lt;element ref="{http://www.visi.nl/schemas/20160331}MessageInTransactionTypeRef"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="sendBefore" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded">
 *                   &lt;element ref="{http://www.visi.nl/schemas/20160331}MessageInTransactionType"/>
 *                   &lt;element ref="{http://www.visi.nl/schemas/20160331}MessageInTransactionTypeRef"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dateLaMu" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="userLaMu" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="helpInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MessageInTransactionTypeConditionType", propOrder = {
    "sendAfter",
    "sendBefore",
    "state",
    "dateLaMu",
    "userLaMu",
    "helpInfo"
})
public class MessageInTransactionTypeConditionType
    extends ElementType
{

    protected MessageInTransactionTypeConditionType.SendAfter sendAfter;
    protected MessageInTransactionTypeConditionType.SendBefore sendBefore;
    protected String state;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateLaMu;
    protected String userLaMu;
    protected String helpInfo;

    /**
     * Gets the value of the sendAfter property.
     * 
     * @return
     *     possible object is
     *     {@link MessageInTransactionTypeConditionType.SendAfter }
     *     
     */
    public MessageInTransactionTypeConditionType.SendAfter getSendAfter() {
        return sendAfter;
    }

    /**
     * Sets the value of the sendAfter property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageInTransactionTypeConditionType.SendAfter }
     *     
     */
    public void setSendAfter(MessageInTransactionTypeConditionType.SendAfter value) {
        this.sendAfter = value;
    }

    /**
     * Gets the value of the sendBefore property.
     * 
     * @return
     *     possible object is
     *     {@link MessageInTransactionTypeConditionType.SendBefore }
     *     
     */
    public MessageInTransactionTypeConditionType.SendBefore getSendBefore() {
        return sendBefore;
    }

    /**
     * Sets the value of the sendBefore property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageInTransactionTypeConditionType.SendBefore }
     *     
     */
    public void setSendBefore(MessageInTransactionTypeConditionType.SendBefore value) {
        this.sendBefore = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the dateLaMu property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateLaMu() {
        return dateLaMu;
    }

    /**
     * Sets the value of the dateLaMu property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateLaMu(XMLGregorianCalendar value) {
        this.dateLaMu = value;
    }

    /**
     * Gets the value of the userLaMu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserLaMu() {
        return userLaMu;
    }

    /**
     * Sets the value of the userLaMu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserLaMu(String value) {
        this.userLaMu = value;
    }

    /**
     * Gets the value of the helpInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHelpInfo() {
        return helpInfo;
    }

    /**
     * Sets the value of the helpInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHelpInfo(String value) {
        this.helpInfo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded">
     *         &lt;element ref="{http://www.visi.nl/schemas/20160331}MessageInTransactionType"/>
     *         &lt;element ref="{http://www.visi.nl/schemas/20160331}MessageInTransactionTypeRef"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "messageInTransactionTypeOrMessageInTransactionTypeRef"
    })
    public static class SendAfter {

        @XmlElements({
            @XmlElement(name = "MessageInTransactionType", type = MessageInTransactionTypeType.class),
            @XmlElement(name = "MessageInTransactionTypeRef", type = MessageInTransactionTypeTypeRef.class)
        })
        protected List<Object> messageInTransactionTypeOrMessageInTransactionTypeRef;

        /**
         * Gets the value of the messageInTransactionTypeOrMessageInTransactionTypeRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the messageInTransactionTypeOrMessageInTransactionTypeRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMessageInTransactionTypeOrMessageInTransactionTypeRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MessageInTransactionTypeType }
         * {@link MessageInTransactionTypeTypeRef }
         * 
         * 
         */
        public List<Object> getMessageInTransactionTypeOrMessageInTransactionTypeRef() {
            if (messageInTransactionTypeOrMessageInTransactionTypeRef == null) {
                messageInTransactionTypeOrMessageInTransactionTypeRef = new ArrayList<Object>();
            }
            return this.messageInTransactionTypeOrMessageInTransactionTypeRef;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded">
     *         &lt;element ref="{http://www.visi.nl/schemas/20160331}MessageInTransactionType"/>
     *         &lt;element ref="{http://www.visi.nl/schemas/20160331}MessageInTransactionTypeRef"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "messageInTransactionTypeOrMessageInTransactionTypeRef"
    })
    public static class SendBefore {

        @XmlElements({
            @XmlElement(name = "MessageInTransactionType", type = MessageInTransactionTypeType.class),
            @XmlElement(name = "MessageInTransactionTypeRef", type = MessageInTransactionTypeTypeRef.class)
        })
        protected List<Object> messageInTransactionTypeOrMessageInTransactionTypeRef;

        /**
         * Gets the value of the messageInTransactionTypeOrMessageInTransactionTypeRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the messageInTransactionTypeOrMessageInTransactionTypeRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMessageInTransactionTypeOrMessageInTransactionTypeRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MessageInTransactionTypeType }
         * {@link MessageInTransactionTypeTypeRef }
         * 
         * 
         */
        public List<Object> getMessageInTransactionTypeOrMessageInTransactionTypeRef() {
            if (messageInTransactionTypeOrMessageInTransactionTypeRef == null) {
                messageInTransactionTypeOrMessageInTransactionTypeRef = new ArrayList<Object>();
            }
            return this.messageInTransactionTypeOrMessageInTransactionTypeRef;
        }

    }

}
