//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.13 at 02:17:24 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.visi.nl/schemas/20140331", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package nl.visi.schemas._20140331;
