//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.03 at 01:18:23 PM CET 
//

package nl.visi_1_1a.interaction_schema;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ElementConditionType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ElementConditionType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.visi.nl/schemas/20070406}elementType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="requiredNotify" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="minValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="maxValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="format" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="helpInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="element">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{http://www.visi.nl/schemas/20070406}SimpleElementType"/>
 *                   &lt;element ref="{http://www.visi.nl/schemas/20070406}SimpleElementTypeRef"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="message">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{http://www.visi.nl/schemas/20070406}MessageType"/>
 *                   &lt;element ref="{http://www.visi.nl/schemas/20070406}MessageTypeRef"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ElementConditionType", propOrder = { "description", "requiredNotify", "minValue", "maxValue",
		"format", "helpInfo", "element", "message" })
public class ElementConditionType extends ElementType {

	@XmlElement(required = true)
	protected String description;
	@XmlElement(required = true)
	protected BigInteger requiredNotify;
	protected String minValue;
	protected String maxValue;
	protected String format;
	protected String helpInfo;
	@XmlElement(required = true)
	protected ElementConditionType.Element element;
	@XmlElement(required = true)
	protected ElementConditionType.Message message;

	/**
	 * Gets the value of the description property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * Sets the value of the description property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDescription(String value) {
		this.description = value;
	}

	/**
	 * Gets the value of the requiredNotify property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getRequiredNotify() {
		return requiredNotify;
	}

	/**
	 * Sets the value of the requiredNotify property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setRequiredNotify(BigInteger value) {
		this.requiredNotify = value;
	}

	/**
	 * Gets the value of the minValue property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMinValue() {
		return minValue;
	}

	/**
	 * Sets the value of the minValue property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMinValue(String value) {
		this.minValue = value;
	}

	/**
	 * Gets the value of the maxValue property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMaxValue() {
		return maxValue;
	}

	/**
	 * Sets the value of the maxValue property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMaxValue(String value) {
		this.maxValue = value;
	}

	/**
	 * Gets the value of the format property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFormat() {
		return format;
	}

	/**
	 * Sets the value of the format property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFormat(String value) {
		this.format = value;
	}

	/**
	 * Gets the value of the helpInfo property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHelpInfo() {
		return helpInfo;
	}

	/**
	 * Sets the value of the helpInfo property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHelpInfo(String value) {
		this.helpInfo = value;
	}

	/**
	 * Gets the value of the element property.
	 * 
	 * @return possible object is {@link ElementConditionType.Element }
	 * 
	 */
	public ElementConditionType.Element getElement() {
		return element;
	}

	/**
	 * Sets the value of the element property.
	 * 
	 * @param value
	 *            allowed object is {@link ElementConditionType.Element }
	 * 
	 */
	public void setElement(ElementConditionType.Element value) {
		this.element = value;
	}

	/**
	 * Gets the value of the message property.
	 * 
	 * @return possible object is {@link ElementConditionType.Message }
	 * 
	 */
	public ElementConditionType.Message getMessage() {
		return message;
	}

	/**
	 * Sets the value of the message property.
	 * 
	 * @param value
	 *            allowed object is {@link ElementConditionType.Message }
	 * 
	 */
	public void setMessage(ElementConditionType.Message value) {
		this.message = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;choice>
	 *         &lt;element ref="{http://www.visi.nl/schemas/20070406}SimpleElementType"/>
	 *         &lt;element ref="{http://www.visi.nl/schemas/20070406}SimpleElementTypeRef"/>
	 *       &lt;/choice>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "simpleElementType", "simpleElementTypeRef" })
	public static class Element {

		@XmlElement(name = "SimpleElementType")
		protected SimpleElementTypeType simpleElementType;
		@XmlElement(name = "SimpleElementTypeRef")
		protected SimpleElementTypeTypeRef simpleElementTypeRef;

		/**
		 * Gets the value of the simpleElementType property.
		 * 
		 * @return possible object is {@link SimpleElementTypeType }
		 * 
		 */
		public SimpleElementTypeType getSimpleElementType() {
			return simpleElementType;
		}

		/**
		 * Sets the value of the simpleElementType property.
		 * 
		 * @param value
		 *            allowed object is {@link SimpleElementTypeType }
		 * 
		 */
		public void setSimpleElementType(SimpleElementTypeType value) {
			this.simpleElementType = value;
		}

		/**
		 * Gets the value of the simpleElementTypeRef property.
		 * 
		 * @return possible object is {@link SimpleElementTypeTypeRef }
		 * 
		 */
		public SimpleElementTypeTypeRef getSimpleElementTypeRef() {
			return simpleElementTypeRef;
		}

		/**
		 * Sets the value of the simpleElementTypeRef property.
		 * 
		 * @param value
		 *            allowed object is {@link SimpleElementTypeTypeRef }
		 * 
		 */
		public void setSimpleElementTypeRef(SimpleElementTypeTypeRef value) {
			this.simpleElementTypeRef = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;choice>
	 *         &lt;element ref="{http://www.visi.nl/schemas/20070406}MessageType"/>
	 *         &lt;element ref="{http://www.visi.nl/schemas/20070406}MessageTypeRef"/>
	 *       &lt;/choice>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "messageType", "messageTypeRef" })
	public static class Message {

		@XmlElement(name = "MessageType")
		protected MessageTypeType messageType;
		@XmlElement(name = "MessageTypeRef")
		protected MessageTypeTypeRef messageTypeRef;

		/**
		 * Gets the value of the messageType property.
		 * 
		 * @return possible object is {@link MessageTypeType }
		 * 
		 */
		public MessageTypeType getMessageType() {
			return messageType;
		}

		/**
		 * Sets the value of the messageType property.
		 * 
		 * @param value
		 *            allowed object is {@link MessageTypeType }
		 * 
		 */
		public void setMessageType(MessageTypeType value) {
			this.messageType = value;
		}

		/**
		 * Gets the value of the messageTypeRef property.
		 * 
		 * @return possible object is {@link MessageTypeTypeRef }
		 * 
		 */
		public MessageTypeTypeRef getMessageTypeRef() {
			return messageTypeRef;
		}

		/**
		 * Sets the value of the messageTypeRef property.
		 * 
		 * @param value
		 *            allowed object is {@link MessageTypeTypeRef }
		 * 
		 */
		public void setMessageTypeRef(MessageTypeTypeRef value) {
			this.messageTypeRef = value;
		}

	}

}
